/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#301800',
        'primary-container': '#4a2c0a',
        'on-primary': '#ffffff',
        'on-primary-container': '#bf9268',
        secondary: '#825500',
        'secondary-container': '#fcb33e',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6d4700',
        tertiary: '#1f1e1b',
        'tertiary-container': '#34332f',
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#50453b',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        'inverse-primary': '#eebd90',
        outline: '#82756a',
        'outline-variant': '#d4c4b7',
        'surface-tint': '#7c5731',
        'primary-fixed': '#ffdcbe',
        'primary-fixed-dim': '#eebd90',
        'secondary-fixed-dim': '#ffb950',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        background: '#fcf9f8',
      },
      fontFamily: {
        headline: ['Domine', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '16px',
        '3xl': '24px',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm-space': '12px',
        'md-space': '24px',
        'lg-space': '48px',
        'xl-space': '80px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      boxShadow: {
        'card': '0 4px 20px rgba(74, 44, 10, 0.08)',
        'card-hover': '0 8px 30px rgba(74, 44, 10, 0.14)',
      },
    },
  },
  plugins: [],
};
